export const PROVIDERS = {
  "fireworks-ai": {
    name: "Fireworks AI",
    max_tokens: 131_000,
    id: "fireworks-ai",
  },
  nebius: {
    name: "Nebius AI Studio",
    max_tokens: 131_000,
    id: "nebius",
  },
  sambanova: {
    name: "SambaNova",
    max_tokens: 8_000,
    id: "sambanova",
  },
  novita: {
    name: "NovitaAI",
    max_tokens: 16_000,
    id: "novita",
  },
  // hyperbolic: {
  //   name: "Hyperbolic",
  //   max_tokens: 131_000,
  //   id: "hyperbolic",
  // },
  local: {
    name: "Local (Ollama)",
    max_tokens: 131_000,
    id: "local",
  },
  openai: {
    name: "OpenAI GPT-4 Nano",
    max_tokens: 131_000,
    id: "openai",
    model: process.env.OPENAI_API_MODEL || "gpt-4.1-nano",
    base_url: process.env.OPENAI_API_URL || "https://api.openai.com/v1",
    api_key: process.env.OPENAI_API_KEY,
  },
  deepseek: {
    name: "DeepSeek Chat",
    max_tokens: 131_000,
    id: "deepseek",
    model: "deepseek-chat",
    base_url: process.env.DEEPSEEK_API_URL || "https://api.deepseek.com/v1",
    api_key: process.env.DEEPSEEK_API_KEY,
  },
  openrouter: {
    name: "OpenRouter (DeepSeek)",
    max_tokens: 131_000,
    id: "openrouter",
    model: "deepseek/deepseek-chat-v3-0324:free",
    base_url: process.env.OPENROUTER_API_URL || "https://openrouter.ai/api/v1",
    api_key: process.env.OPENROUTER_API_KEY,
  },
  anthropic: {
    name: "Anthropic Claude 3",
    max_tokens: 131_000,
    id: "anthropic",
    model: "claude-3-haiku-20240307",
    base_url: process.env.ANTHROPIC_API_URL || "https://api.anthropic.com/v1",
    api_key: process.env.ANTHROPIC_API_KEY,
  },
  together: {
    name: "Together AI",
    max_tokens: 131_000,
    id: "together",
    model: "mistralai/Mixtral-8x7B-Instruct-v0.1",
    base_url: process.env.TOGETHER_API_URL || "https://api.together.xyz/v1",
    api_key: process.env.TOGETHER_API_KEY,
  },
  groq: {
    name: "Groq",
    max_tokens: 131_000,
    id: "groq",
    model: "meta-llama/llama-4-maverick-17b-128e-instruct",
    base_url: process.env.GROQ_API_URL || "https://api.groq.com/openai/v1",
    api_key: process.env.GROQ_API_KEY,
  },
  deepinfra: {
    name: "DeepInfra",
    max_tokens: 131_000,
    id: "deepinfra",
    model: "Qwen/Qwen2.5-Coder-32B-Instruct",
    base_url: process.env.DEEPINFRA_API_URL || "https://api.deepinfra.com/v1/openai",
    api_key: process.env.DEEPINFRA_API_KEY,
  },
  mistral: {
    name: "Mistral AI",
    max_tokens: 131_000,
    id: "mistral",
    model: "codestral-latest",
    base_url: process.env.MISTRAL_API_URL || "https://api.mistral.ai/v1",
    api_key: process.env.MISTRAL_API_KEY,
  },
  cohere: {
    name: "Cohere Command",
    max_tokens: 131_000,
    id: "cohere",
    model: "command-r-plus",
    base_url: process.env.COHERE_API_URL || "https://api.cohere.ai/v1",
    api_key: process.env.COHERE_API_KEY,
  }
};
